import prisma from "./prisma";
import { cache } from "react";
import { CompanySettings } from "@prisma/client";

export const getCompanySettings = cache(async (): Promise<CompanySettings> => {
  const settings = await prisma.companySettings.findUnique({
    where: { id: "singleton" },
  });

  if (!settings) {
    // Fallback if DB was not seeded for some reason
    return {
      id: "singleton",
      companyName: "Shree TBTC Global Industries",
      logoUrl: null,
      faviconUrl: null,
      activeTheme: "theme1",
      primaryColor: "#0b3c5d",
      secondaryColor: "#d9534f",
      accentColor: "#328cc1",
      backgroundColor: "#ffffff",
      darkSectionColor: "#0f172a",
      textColor: "#334155",
      buttonColor: "#0b3c5d",
      buttonHoverColor: "#0d4870",
      linkColor: "#0b3c5d",
      email: "info@stbtcgi.in",
      phoneNumbers: "+91-9331404702, +91-8240450043, +91-9038707773",
      whatsAppNumber: "+919331404702",
      address: "Flat No: 302, 14/1 Sree Kishen Bhakat Lane, Howrah - 711101, West Bengal, India",
      city: "Howrah",
      state: "West Bengal",
      country: "India",
      postalCode: "711101",
      gstNumber: "",
      businessHours: "Monday – Saturday (10:00 AM – 05:00 PM)",
      googleMapsEmbed: null,
      enableTopContactBar: true,
      topBarTitle: "DEALER & IMPORTER",
      topBarConfig: null,
      mobileLogoUrl: null,
      headerCtaText: "Request Quote",
      headerCtaLink: "/quote",
      enableHeaderSearch: true,
      enableStickyHeader: true,
      navigationConfig: null,
      sliderAutoplay: true,
      sliderAutoplaySpeed: 5000,
      sliderTransitionStyle: "fade",
      sliderTransitionSpeed: 500,
      sliderShowArrows: true,
      sliderShowDots: true,
      sliderHeight: "h-[600px]",
      introEnabled: true,
      introHeading: "Who We Are",
      introHighlightHeading: "Shree TBTC Global Industries",
      introSubtitle: "Your Trusted Industrial Procurement Partner",
      introDescription: "Founded with the goal of bringing robust industrial procurement to global standards...",
      introImages: null,
      introCtaText: "Read Our Profile",
      introCtaLink: "/about",
      introCtaStyle: "primary",
      introBgColor: "#ffffff",
      introTextColor: "#334155",
      introLayoutStyle: "left-image",
      homeCategoriesLimit: 6,
      homeCategoriesLayout: "grid",
      homeFeaturedProductsEnabled: true,
      homeFeaturedProductsHeading: "Featured Products",
      homeFeaturedProductsSubtitle: "High-Quality Industrial Supplies",
      homeFeaturedProductsLimit: 6,
      homeFeaturedProductsCtaText: "View All Products",
      homeFeaturedProductsCtaLink: "/products",
      homeFeaturedProductsLayout: "grid",
      whyWorkEnabled: true,
      whyWorkHeading: "Why Work With Shree TBTC",
      whyWorkHighlight: "Shree TBTC",
      whyWorkSubtitle: "Our Commitment to Quality",
      whyWorkDescription: "We supply certified products directly from manufacturers to minimize downtime.",
      whyWorkBgColor: "#f8fafc",
      whyWorkTextColor: "#334155",
      whyWorkImage: null,
      whyWorkLayout: "left-content",
      homeIndustriesEnabled: true,
      homeIndustriesHeading: "Industries We Serve",
      homeIndustriesSubtitle: "Sectors We Support",
      homeIndustriesDescription: "Catering to critical processing, refining and transmission sectors.",
      homeIndustriesBgColor: "#ffffff",
      homeIndustriesTextColor: "#334155",
      homeIndustriesLayout: "grid",
      homeCtaEnabled: true,
      homeCtaHeading: "Looking for a specific Industrial Component or custom steel order?",
      homeCtaHighlight: "Industrial Component",
      homeCtaDescription: "Talk to our technical sales experts for stock checks and pricing.",
      homeCtaBgColor: "#0b3c5d",
      homeCtaBgImage: null,
      homeCtaBgOverlay: 0.8,
      homeCtaTextColor: "#ffffff",
      homeCtaButtons: null,
      footerConfig: null,
      copyrightText: "© {year} Shree TBTC Global Industries. All Rights Reserved.",
      copyrightLink: "",
      devCreditText: "Created & Developed By Webz Technologies",
      devCreditLink: "https://webztechnologies.com/",
      devCreditEnabled: true,
      devCreditOpenInNewTab: true,
      aboutHeroTitle: "About Our Company",
      aboutHeroSubtitle: "Your Trusted Partner in Industrial Procurement",
      aboutHeroBgImage: null,
      aboutHeroCtaText: null,
      aboutHeroCtaLink: null,
      aboutStoryHeading: "One-Stop Source for Switchgear, Steels, Lubricants & Insulators",
      aboutStoryContent: "Established as a primary supply hub in Howrah...",
      aboutStoryImages: null,
      aboutStoryHighlights: null,
      aboutMissionHeading: "Our Mission",
      aboutMissionContent: "To supply high-grade parts directly from manufacturer channels...",
      aboutMissionImage: null,
      aboutVisionHeading: "Our Vision",
      aboutVisionContent: "To become the leading B2B global industrial procurement house...",
      aboutVisionImage: null,
      aboutValuesConfig: null,
      aboutStatsConfig: null,
      aboutTeamConfig: null,
      aboutCertificationsConfig: null,
      aboutCtaConfig: null,
      homepageSectionsConfig: null,
      seoTitleDefault: "Shree TBTC Global Industries | Industrial Electrical & Automation",
      seoDescriptionDefault: "Shree TBTC Global Industries is a leading importer and dealer of Electrical Switchgear, Industrial Steels, Lubricants/Greases, Compressor Filters, and Tip Insulators.",
      createdAt: new Date(),
      updatedAt: new Date()
    };
  }

  return settings;
});
